Removed test coverage for now - bulma-tooltip breaks it
  SyntaxError: Unexpected token '('
  at webpack:///~/vue-bulma-tooltip/src/index.js:25:0 <- index.js:37163